<a href="https://colab.research.google.com/github/jsdhami/Python-For-Research/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is Numpy?
- Numpy is a python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices. Numpy was created in 2005 by Travis Olliphant. It is an open source project and you can use it freely. Numpy stands for Numerical Python.

# Why Numpy?
- In Python we have lists that serve the purpose of arrays, but they are slow to process. Numpy aims to provide an array object that is up to 50x faster than traditional Python lists. The array object in Numpy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy. Arrays are very frequently used in data science, where speed and resources are very important.

# Why is Numpy Faster?
- Numpy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently. This behavior is called locality of reference in computer science. This is the main reason why Numpy is faster than lists. Also it is optimized to work with latest CPU architectures.

# Which Language is Numpy written in?
- Numpy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

In [ ]:
# install numpy module using pip package manager
pip install numpy

In [ ]:
# importing the numpy module
import numpy

Or

In [ ]:
# import numpy module as np
import numpy as np

In [ ]:
# Checking version of numpy module
print("Version:", np.__version__)

Version: 1.26.4


In [ ]:
# Creating an array using numpy
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

# checking the type of array
print("type of array:", type(arr))

Array: [1 2 3 4 5]
type of array: <class 'numpy.ndarray'>


In [ ]:
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


In [ ]:
# Dimension on array
# 0-D array means the array has 0 dimensions and it is a scalar value in numpy
zero_dimension = np.array(2)
print("0-D array:", zero_dimension)


0-D array: 2


In [ ]:
# 1-D array means the array has 1 dimension and it is a vector in numpy
one_dimension = np.array([1, 2, 3, 4, 5])
print("1-D array:", one_dimension)



1-D array: [1 2 3 4 5]


In [ ]:
# 2-D array means the array has 2 dimensions and it is a matrix in numpy
two_dimension = np.array([[1, 2, 3],
                          [4, 5, 6]])
print(two_dimension)
print(two_dimension.ndim) # checking the dimension of array
print(two_dimension.shape) # checking the shape of array

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [ ]:

# 3-D array means the array has 3 dimensions and it is a matrix in numpy
three_dimension = np.array([[[1, 2, 3],[4, 5, 6],[5,5,5]],
                            [[7, 8, 9],[1, 1, 2],[5,5,6]],
                            [[1, 2, 3],[4, 5, 6],[5,5,5]]])
print(three_dimension)
print(three_dimension.ndim) # checking the dimension of array
print(three_dimension.shape) # checking the shape of array
print(three_dimension.size) # checking the size of array

[[[1 2 3]
  [4 5 6]
  [5 5 5]]

 [[7 8 9]
  [1 1 2]
  [5 5 6]]

 [[1 2 3]
  [4 5 6]
  [5 5 5]]]
3
(3, 3, 3)
27


In [ ]:
# 4-D array means the array has 4 dimensions and it is a matrix in numpy
four_dimension = np.array([[[[1, 2, 3],[4, 5, 6],[5,5,5]],
                            [[7, 8, 9],[1, 1, 2],[5,5,6]],
                            [[1, 2, 3],[4, 5, 6],[5,5,5]]],
                           [[[1, 2, 3],[4, 5, 6],[5,5,5]],
                            [[7, 8, 9],[1, 1, 2],[5,5,6]],
                            [[1, 2, 3],[4, 5, 6],[5,5,5]]]])
print(four_dimension)
print(four_dimension.ndim) # checking the dimension of array
print(four_dimension.shape) # checking the shape of array
print(four_dimension.size) # checking the size of array

[[[[1 2 3]
   [4 5 6]
   [5 5 5]]

  [[7 8 9]
   [1 1 2]
   [5 5 6]]

  [[1 2 3]
   [4 5 6]
   [5 5 5]]]


 [[[1 2 3]
   [4 5 6]
   [5 5 5]]

  [[7 8 9]
   [1 1 2]
   [5 5 6]]

  [[1 2 3]
   [4 5 6]
   [5 5 5]]]]
4
(2, 3, 3, 3)
54


In [ ]:
# Create a 5-D array with values 1,2,3,4 and verify the dimension of array

five_dimension = np.array([1, 2, 3, 4], ndmin=5)
print(five_dimension)
print(five_dimension.shape)
print(five_dimension.ndim)
print("Solved by Janak")

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)
5
Solved by Janak


In [ ]:
# read csv file
